### ISSUE TITLE
Docs have poor spacing

### ISSUE THREAD

**Issue by hayk-skydio** [symforce-org/symforce#141]
**Describe the bug**
The docs pages have very poor formatting between entries.

**To Reproduce**
Look at any docs pages, for example https://symforce.org/api/symforce.cam.camera.html

**Expected behavior**
Clearer formatting

**Screenshots**
<img width="897" alt="image" src="https://user-images.githubusercontent.com/79281715/170033349-204cfe82-9399-4956-ab03-ae92be9c1512.png">

**Comment by aaron-skydio** [comment]
This is the issue: https://github.com/bitprophet/alabaster/issues/181
