### ISSUE TITLE
missing eigen_lcm types in cmake build / install

### ISSUE THREAD

**Issue by asa** [symforce-org/symforce#151]
**Describe the bug**
In source builds using cmake the eigen_lcm cpp headers(eg `lcmtypes/eigen_lcm/MatrixXd.hpp`) are not available.  

**To Reproduce**
```mkdir /tmp/symforce_build
cmake -S /path/to/source -DCMAKE_INSTALL_PREFIX=/opt/symforce -B /tmp/symforce_build
cd symforce_build
make -j{n}
make install
find /opt/symforce |grep eigen_lcm
```

**Expected behavior**
The eigen lcm types should be installed into the install directory during the install step
these are available in the source dir: `third_party/eigen_lcm/lcmtypes/eigen_lcm_lcm/cpp/lcmtypes/eigen_lcm`

**Environment (please complete the following information):**
 - OS and version: Ubuntu Linux 20.04 
 - Python version 3.8.5]
 - SymForce Version: aba8ef79b75d0e8c2eb7ccc270a8923aeb13613a

**Comment by aaron-skydio** [comment]
Thanks, should be fixed by #152 .  Let me know if that doesn't work
