### ISSUE TITLE
Derivative of `sympy.Mod` is 0

### ISSUE THREAD

**Issue by aaron-skydio** [symforce-org/symforce#163]
**Describe the bug**
The derivative of `sympy.Mod` is 0, which breaks the README example on the sympy backend (and anything else that relies on `Mod`)

**To Reproduce**
```python
>>> import symforce
>>> symforce.set_backend("sympy")
>>> from symforce import sympy as sm
>>> x = sm.Symbol(x)
>>> sm.Mod(x, 1).diff(x)
0
```

**Expected behavior**
`sm.Mod(x, 1).diff(x)` should be 1

See also https://github.com/symforce-org/symforce/issues/153#issuecomment-1146897160

**Comment by hayk-skydio** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/79281715/172270132-105d541f-fc1b-4b05-87ec-471a4bfbb6ab.png">

I think plain sympy doesn't have a derivative for mod? But we add `setattr(sympy.Mod, "_eval_derivative", lambda s, v: sympy.S.Zero)` in `symforce/__init__.py`. This could be a bug as it's next to floor and sign, which actually have zero derivatives.

**Comment by aaron-skydio** [comment]
Ah yep, that's it, we should move that into `initialization.py`.  I believe the correct derivative is
`sm.Mod(a, b).diff(a) = 1` and `sm.Mod(a, b).diff(b) = -floor(a/b)`?

Since
```
mod(a, b) = a - b * floor(a/b)
```

(although I'm not sure how sympy mod is defined when a and/or b are negative...)

**Comment by hayk-skydio** [comment]
That sounds right to me. Seems worth checking the negative behavior and matching that with the derivative (hopefully it matches the floor expression you wrote.
