### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by joansola** [symforce-org/symforce#217]
**Describe the bug**
These are not code bugs but documentation errors -- which I consider bugs

- [ ] inverse() : "compose(a,inverse(a)) = a" should be "compose(a,inverse(a)) = identity"
- [ ] local_coordinates() : 
   "Implementation is simply to_tangent(between(this, b)). Tangent space perturbation that conceptually represents “this - a”."
   
   should be
   
   "Implementation is simply to_tangent(between(this, b)). Tangent space perturbation that conceptually represents “this - b”."
   
   also, I think it should be

   "Implementation is simply to_tangent(between(this, b)). Tangent space perturbation that conceptually represents “b - this”."
   
   also, `between()` does not appear listed in the list of available methods, so the doc above is confusing.

**To Reproduce**
Not relevant

**Expected behavior**
Not relevant

**Screenshots**
 - SymForce webpage documentation on Aug 26, 2022

**Comment by hayk-skydio** [comment]
Thank you for pointing this out @joansola!
