### ISSUE TITLE
Install the symforce_slam library

### ISSUE THREAD

**Issue by johhat** [symforce-org/symforce#310]
**Is your feature request related to a problem? Please describe.**
In my case I'd like to use the new imu_factor in the symforce_slam library in a standalone CMake project. However, at the moment the symforce_slam library is not installed when following the official [CMake build instructions](https://github.com/symforce-org/symforce#build-with-cmake) and using `make install`.

I've submitted PR https://github.com/symforce-org/symforce/pull/309 to install the symforce_slam library in the same manner as symforce_opt and symforce_gen.

**Describe the solution you'd like**
Install the symforce_slam library such that it can be found with CMake using e.g.
```CMake
find_library(
    SYMFORCE_SLAM
    symforce_slam
)
```

**Comment by aaron-skydio** [comment]
Fixed by #309
