### ISSUE TITLE
AssertionError: Cannot compute a linearization with respect to 0 arguments

### ISSUE THREAD

**Issue by VineetTambe** [symforce-org/symforce#318]
I am trying to run the sf.optimizer:
here is how I create my optimizer: 
```
optimizer = Optimizer(
    factors=factors,
    optimized_keys=_optimized_keys,
    debug_stats=True,  # Return problem stats for every iteration
    params=Optimizer.Params(verbose=True),  # Customize optimizer behavior
)
```

But the above line throws the following assertion error: 
```AssertionError: Cannot compute a linearization with respect to 0 arguments```

This is how create ```_optimized_keys,```
```_optimized_keys = [f"nodes[{i}]" for i in range(_num_nodes)]```

All my sub functions do have arguments. So I do not understand where exactly am I going wrong.

Please let me know if you need any more logs or sys info.
Thanks in advance!

**Comment by aaron-skydio** [comment]
Mostly it would be useful to know the factors you're using, and the stack trace - it would be good to update that error message to be a ValueError instead of an assert, and include 1) the name of the factor, if present, and 2) probably `self.inputs.keys()` (the names of the inputs to the factor)

**Comment by VineetTambe** [comment]
This is how I am building my factors: 
```
def build_factors(num_nodes: int) -> T.Iterator[Factor]:
    """
    Build factors for a problem of the given dimensionality.

    TODO: this looks wrong -> figure it out 


    """
    
    for i in range(num_nodes - 1):
        yield Factor(
            residual=residual,
            keys=[f"poses[{i}]", 
                  f"nodes[edges[{i},0]]", 
                  f"nodes[edges[{i},1]]", 
                #   "epsilon"
                  ],
        )
    
    yield Factor(
            residual=prior_residual,
            keys=[f"nodes[{0}]"
                  ],
        )
```

And this is how I am adding the keys:
```
_optimized_keys = [f"nodes[{i}]" for i in range(1, _num_nodes)]
```

**Comment by bradley-solliday-skydio** [comment]
Hey Vineet. It looks like the reason you're getting an error is because none of the keys in your factors actually match the keys you constructed your `Optimizer` with. Ex: `"nodes[edges[4, 0]]" != "nodes[4]"`.

If there is actually an `edges` variable whose values are indices for `"nodes"`, then perhaps what you mean to do is build your factors like this:
``` python
def build_factors(num_nodes: int) -> T.Iterator[Factor]:
   
    for i in range(num_nodes):
        yield Factor(
            residual=residual,
            keys=[f"poses[{i}]", 
                  f"nodes[{edges[i][0]}]",  # <-- this line is different
                  f"nodes[{edges[i][1]}]",  # <-- this line is different
                #   "epsilon"
                  ],
        )
```
so that, if `edges[4][0] == 2`, then `["poses[4]", "nodes[2]", f"nodes[{edges[4][1]}]"]` would have non-empty intersection with `_optimized_keys` `["nodes[0]", "nodes[1]", "nodes[2]", "nodes[3]", "nodes[4]", ...]`

More generally, in order for, say, the 2nd argument of a residual to be optimized, the second key in the factor you construct from it (so `"nodes[edges[4][0]]"`) would have to exactly match one of the keys in `_optimized_keys` that you construct the `Optimizer` with.

Conceptually, if none of the keys match, then the factor wouldn't actually do anything. Incidentally, what happens is an `AssertionError` is raised, as you saw.

**Comment by bradley-solliday-skydio** [comment]
Regarding Aaron's comment, I agree that the current error message is inadequate. I'd like to modify `Optimizer.__init__` to add this check:

```python
        for factor in factors:
            if isinstance(factor, Factor):
                if optimized_keys is None:
                    raise ValueError(
                        "You must specify keys to optimize when passing symbolic factors."
                    )
                # We compute the linearization in the same order as `optimized_keys`
                # so that e.g. columns of the generated jacobians are in the same order
                factor_opt_keys = [opt_key for opt_key in optimized_keys if opt_key in factor.keys]
                # PROPOSED ADDITION vvv
                if len(factor_opt_keys) == 0:
                    raise ValueError(
                        f"Factor {factor.name} has no arguments (keys: {factor.keys}) in "
                        + f"optimized_keys ({optimized_keys})."
                    )
                # END PROPOSED ADDITION ^^^
                numeric_factors.append(factor.to_numeric_factor(factor_opt_keys))
```

**Comment by VineetTambe** [comment]
Okay got it thanks - basically my error was a key mismatch error.

**Comment by VineetTambe** [comment]
I want to ask - How do I specify a compound optimisation key - for ex.
In my case my residual accepts ```nodes[edges[{i}][0]]]``` and  ```nodes[edges[{i}][1]]]``` as an argument. 
And I want to optimize for the nodes in the dataset - However when I specify
```
_optimized_keys = [f"nodes[edges[{i}][0]]" for i in range( _num_nodes)]
```
I get the error: 
```
InvalidKeyError                           Traceback (most recent call last)
Cell In[16], line 2
      1 # Solve and return the result
----> 2 result = optimizer.optimize(_values)

File [~/symForce/env/lib/python3.10/site-packages/symforce/opt/optimizer.py:247](https://file+.vscode-resource.vscode-cdn.net/home/vrex/symForce/symforce_ws/pose_graph_opt/src/~/symForce/env/lib/python3.10/site-packages/symforce/opt/optimizer.py:247), in Optimizer.optimize(self, initial_guess)
    235 def optimize(self, initial_guess: Values) -> Optimizer.Result:
    236     """
    237     Optimize from the given initial guess, and return the optimized Values and stats
    238 
   (...)
    245         `Optimizer.Result` documentation for more information
    246     """
--> 247     cc_values = self._cc_values(initial_guess)
    249     try:
    250         stats = self._cc_optimizer.optimize(cc_values)

File [~/symForce/env/lib/python3.10/site-packages/symforce/opt/optimizer.py:231](https://file+.vscode-resource.vscode-cdn.net/home/vrex/symForce/symforce_ws/pose_graph_opt/src/~/symForce/env/lib/python3.10/site-packages/symforce/opt/optimizer.py:231), in Optimizer._cc_values(self, values)
    229 cc_values = cc_sym.Values()
    230 for key, cc_key in self._cc_keys_map.items():
--> 231     cc_values.set(cc_key, values[key])
    233 return cc_values

File [~/symForce/env/lib/python3.10/site-packages/symforce/values/values.py:670](https://file+.vscode-resource.vscode-cdn.net/home/vrex/symForce/symforce_ws/pose_graph_opt/src/~/symForce/env/lib/python3.10/site-packages/symforce/values/values.py:670), in Values.__getitem__(self, key)
...
--> 219     raise InvalidKeyError(f"{indexed_array} is not a base and its indices")
    220 base, indices_str = base_indices_match.groups()
    221 indices = [int(match.group()) for match in re.finditer(r"[0-9]+", indices_str)]
InvalidKeyError: nodes[edges[0][0]] is not a base and its indices
```
So does the relative order of the optimisation keys also matter when I pass them as arguments to Optimizer?

**Comment by VineetTambe** [comment]
Managed to solve it: 
For some reason I was thinking that I had to do some fancy python stuff to solve this:
The solution was simple - I just stored the values of edges[i][0] and edges[i][1] in temporary variables and passed those vars when I was creating the factors!

**Comment by VineetTambe** [comment]
I had a basic question - 
Lets say my factors have keys ```nodes[edges[i][0]]```
Will I still be optimising for keys ```nodes[i]``` or would my optimisation_keys be ```nodes[edges[i][0]]```?

**Comment by bradley-solliday-skydio** [comment]
Sorry for the delay (didn't notice your last message). But it's the latter, your optimization keys would need to be `nodes[edges[i][0]]`, as the `Optimizer` just does a simple string compare of the optimization_keys with the factors keys to figure out which ones to optimize.
