### ISSUE TITLE
Use `ninja` build tool

### ISSUE THREAD

**Issue by KOLANICH** [symforce-org/symforce#331]
**Is your feature request related to a problem? Please describe.**
`ninja` is a build tool that tries to do building faster than `make` by tracking dependency graph and changes in the files. It may make sense to use it for building.

**Describe the solution you'd like**
`-GNinja` argument for CMake and `ninja` instead of `make.

**Comment by aaron-skydio** [comment]
We're also fans of `ninja` :)

But, we generally aren't trying to force defaults on users or make them install more than necessary.  In particular, although we haven't really tested this, we don't want to stop people from using e.g. generators from various IDEs and such.

You're welcome to set `-GNinja` while running the CMake build, or use the `CMAKE_GENERATOR` environment variable (I've built SymForce with Ninja this way) - if something doesn't work on Ninja that's also something we should fix, feel free to open an issue
