### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Babayevaterane** [symforce-org/symforce#345]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Create file '...'
2. Run '...'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: [e.g. Ubuntu Linux 20.04]
 - Python version [e.g. 3.10]
 - SymForce Version [e.g. 0.3.0 or af687c1]

**Additional context**

**Comment by bradley-solliday-skydio** [comment]
Hey Babayevaterane. Did you mean to submit this issue? It doesn't actually contain a description of a problem.
