### ISSUE TITLE
Error in camera filtering for bundle_adjustment_in_the_large example

### ISSUE THREAD

**Issue by MGBzH** [symforce-org/symforce#408]
The example `bundle_adjustment_in_the_large.cc` first loads observations, camera poses with intrinsics and points from a text file. Then the function `FilterCameraOutliers` is called to remove cameras that are wrongly initialized being too far from the centroid of all the cameras. 
However this function seems to remove too many factors. On the problem 21-11315, 36455 factors and 21 cameras are fed to this function which returns only 21 factors that are then optimized. 
I don't think this problem contains any wrongly initialized camera, so I think all the factors should be kept?
I assume that the error is coming from l. 62 where a single factor per camera is kept in the `filtered_factors` instead of keeping all the factors connected to the good camera.

**Comment by aaron-skydio** [comment]
Thanks, this was already fixed in our internal copy by https://github.com/symforce-org/symforce/commit/5f4079eed278d8523086b87c46f77aaab4d6d794, just got around to exporting that to the open-source copy.  See the commit message there for some more information about what's going on
